version : '3'
services:
    mysql:
      image: mysql:5.7
      volumes:
        - mysql_data:/var/lib/mysql
      environment:
        - MYSQL_ALLOW_EMPTY_PASSWORD=no
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      networks:
        - default
    smtp:
      image: namshi/smtp
volumes:
    mysql_data:
      driver: local